### ISSUE TITLE
Add an Accordion Content Block

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#105]
JCU people are used to using accordion format from the regular site and adding one in our site (following the instructions for the main site - https://www.jcu.edu.au/digital-marketing/web-guides-and-advice/accordions). It kind of works but looks crap.
We need to create our own Accordion content block and make it look good and possibly disable the other format.
One of the problems with the existing accordion behaviour (aside from ugliness) is that a CTRL+F on the page cannot find content when the accordions are collapsed. 
Options:
- [ ] Never collapse but provide a Contents section above the content?
- [ ] Allow collapsing but provide expand all and collapse all options?
- [ ] Make it not be heavy and ugly looking!

**Comment by davidjb** [comment]
For the record, I dislike accordions (the UI element; I ❤️ the instrument) but given existing advocacy to use them and since we've seen people trying to follow the existing instructions I agree that we probably need to add one.  Perhaps we can *try* to get people to only use these when there's multiple pathways to follow, rather than just using them as they do now to squish tonnes more content together.

Web framework designs are at https://web.jcu.io/jcu/accordion/ which followed the original implementation in the main site; changes are welcome.  Changing the colour on the headings is fairly easy -- just add say a `.bg-danger` to a `.jcu-accordion__toggle` and you've got red.

Another concern is that Matrix doesn't provide "multi WYSIWYG" metadata fields -- so we'd need to set an upper limit on how many sections the accordion could have, and define a field for each (eg `template.accordion.title{1,2,3,4,5}` and `template.accordion.content{1,2,3,4,5}`).  This means the editing interface is stuck showing all these elements and load times skyrocket as the resource-munching Viper WYSIWYG editor gets loading 5x or 10x.  Plus, from a editor's point of view, they can't easily reorder sections -- they'd need to copy out content and move it manually.  But hey, that's Matrix. 

Or, we go entirely the other way and just do what the main Matrix site does -- have people define headings in a certain way and it "magically" turns it into an accordion.  This goes against the principle of WYSIWYG, but we might have to do this to allow arbitrary numbers of sections.  Then again, there's probably a better way if someone needs 10 accordion sections...

As for search, short of intercepting the keydown events in JS, there's not much you could do.  Afaict, there's no [event](https://developer.mozilla.org/en-US/docs/Web/Events) for an on-search so even if you trapped Ctrl-F and ⌘-F, you'll still be stuck on any device without a keyboard (eg mobile).

**Comment by PaulineLawrey** [comment]
After discussion within the team we have decided to not implement an accordion at this time as there is no actual use case for one that can't easily be handled by existing functionality. This may be something we implement in the future as funding and time becomes available. Perhaps something along the lines of the process steps where a content block is created for each fold in the accordion.
