### ISSUE TITLE
Basic Block - Using Link assets for Optional Picture no longer works as a link

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#121]
Before the recent changes for Basic Block images to be shown in a lightbox by default it was possible to use a Link asset as the Optional Picture and clicking on the picture would redirect you to the linked asset (either  PDF , another Page asset or external URL).

This no longer works as the lightbox takes control.  I think we need the Link functionality.

**Comment by davidjb** [comment]
As per Slack, we're stuck because we already have to render out %keywords% from SSJS to bring inthe Related Asset renderer.  This means we can't run anything *after* that to determine if the asset should or shouldn't in a lightbox.   In our loop in SSJS, we can't look up an asset's type either (because data only goes in one way via keywords).

I could imagine a solution *could* be possible, but we'd have to use conditional keywords to somehow meta-construct SSJS which then prints keywords to render the Paint Layout...and I've just had a brain meltdown trying to think about it.

As a cleaner option, how about we add that option to disable the lightbox entirely in this type of Block so then it a) works and b) is a bit more clear for the user what they're opting in for.  We can then give them helpful hints as to when a user might disable the lightbox.

**Comment by davidjb** [comment]
Added the metadata option to disable lightbox functionality; it's enabled by default for all existing Blocks.
