### ISSUE TITLE
Links on blocks with a background image can be difficult to read

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#122]
See https://www.jcu.edu.au/tropical-fisheries-and-aquaculture/people/_noproxycache

If the content on a **Text With Styled Background** content block contains links and the background is dark then the linked text is difficult to read.

**Comment by davidjb** [comment]
Because we can't know what background image (and therefore its colour) people might pick -- and also how an image is laid out depends on the device -- we need to make the Editors aware that they can change and need to change the link colour in the editor if readability is an issue.  

For example, see the second Block down at https://www.jcu.edu.au/vislab.  I did that by clicking the link in the Editor, clicking the Paint drop button, then choosing a relevant `Text (...)` style (in my case, `Text (info)`).

In the same vein, it'd be helpful to inform editors that the background image will shift depending on a person's screen size and device so as not to get them to rely on the content specifically (in this case, the colour in any one particular area).

**Comment by DanielBaird** [comment]
We make normal text white, so we are assuming a dark-ish background image. Probably we should make link colours a bit lighter by default so they're dark-background friendly.

If we were *really* fancy, we'd sniff the colour they choose and switch between light-text and dark-text based on that...
