### ISSUE TITLE
Image Gallery and other images add Disable Link option?

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#139]
There are cases where there is nothing to be gained by having the images link to a larger version of themselves and having them show as links when you hover leads to confusion when you click on it thinking it is important and all you gets is a coloured block with a couple of words on it. e.g.
https://www.jcu.edu.au/international-symposium-of-genetics-in-aquaculture/draft/home/_noproxycache

See the Conference Themes and Objectives section.

**Comment by davidjb** [comment]
To achieve this, we'd have to rewrite the Asset Related Image Paint Layout and change how it accepts "arguments" -- following the `this.args` of Content Block common paint layouts.  Assuming no show-stopper technical problems or SSJS weirdness, I'm in favour of doing this to make its usage clearer and well-defined.

So, we'd go from:

```
%asset_metadata_template.picture.picture^as_asset:asset_contents_paint_374698^replace:#image_class#:img-fluid^replace:#link_class#:link-gallery%
```

to being something like:

```html
<script runat="server">this.args = {image_class: 'img-fluid', link_class: 'link-gallery'}</script>
%asset_metadata_template.picture.picture^as_asset:asset_contents_paint_374698%
```

and in the `this.args` we can then define an arg like `link_enabled` and omit the `<a>` tag if it's false.

The only other thing to consider is a situation where someone wants specific assets (eg `Link`) linked but not others.  In that case, I'd vote for always linking `Links`, if present, because that's what the editor is declaring they want.

Any other thoughts?

(CC @DanielBaird)

**Comment by DanielBaird** [comment]
In @PaulineLawrey 's example the problem is that clicking a theme's image/title should show more information about the theme -- Image Gallery isn't being used to show a list of images, but a list of "themes" that as an implementation detail happen to be represented as images.

I agree a "don't link images to themselves" setting on Image Gallery would support this use case, and by phrasing it that way we can always make Link assets clickable, so the user has the power to have some gallery items linked up and some not.

**Comment by davidjb** [comment]
I've implemented this with the same strategy as Basic Blocks and Process Steps -- you can disable linking for the whole gallery.  Trying to do it for individual images is really hard so it's either all-or-nothing.  I made the change for you @PaulineLawrey  at https://www.jcu.edu.au/international-symposium-of-genetics-in-aquaculture. :)
