### ISSUE TITLE
CCT Text plus optional title, pic, buttons - title included when empty

### ISSUE THREAD

**Issue by PaulineLawrey** [jcu-eresearch/matrix-helpers#86]
If you leave all the settings as per default and just add text or text and a picture then you end up with too much white space at the top of the content block. This is because of the empty h3 tags generated.

Selecting Title Visibility > Hide Title and Subtitle fixes this problem but it doesn't seem reasonable that the user who doesn't enter a title should have to go in and chose to hide the title they didn't enter.

**Comment by davidjb** [comment]
We're limited in what we can do here because we need to check the resultant contents of the title *and* subtitle after they're both processed to strip off any non-phasing HTML.  Because this can only happen after SSJS has run, our current solution of having Matrix do the processing *afterwards* makes the current implementation unworkable.  

However, if we were able to get HTML parsing/stripping *inside* the SSJS, then we could parse the raw value there, and then use a simple `if` statement to only output what actually has a value.  I had a look around for solution to this a while back, but a non-browser, non-Node, completely vanilla JS HTML dom/parser isn't an easily thing to find -- if it exists at all (that means not for Node or anything that uses a `document` object).  In an hour's search, I managed to find a HTML4 parser (http://ejohn.org/blog/pure-javascript-html-parser/) and `dom.js` (a DOM implemented with ES6, which we don't have, but could *try* to get working via transpiling, but it definitely doesn't work OOTB).  If we can find an implementation that fits that bill, then we can try and find a solution in SSJS, but the complexity increases with each step.

A better solution could be #55, but only if that API allowed us to run keyword modifiers arbitrarily.

For now, feel free to look around for a solution in pure/vanilla JS (or works in v8js) but it's not something very common.  We're in a very strange environment, and because Node.js is so common, that's what code is being developed for.

Going to mark this as "can't fix" for now, but feel free to revisit if things change.

**Comment by davidjb** [comment]
Actually, just go ahead and ignore everything I said above.  After talking with @DanielBaird, we concluded all we actually need to do here is test whether the values of title/subtitle are fully empty -- eg precisely equal to the string of `<p></p>` and then use that to make a call.  That handles the initial user experience of creating a Content Block and it'll display correctly, hiding the divs and `<hr>` until they enter something.  The only time this will look a touch odd is if someone accidentally leaves some form of block content (like `<div><br></div>`) in their title/subtitle fields without any actual text.  This is unlikely, and we can always document this edge case.  

Stay tuned for an incoming commit to fix this problem.  It also greatly simplifies how the CCTs work to render the title/subtitle and their contents.  Woo!

**Comment by davidjb** [comment]
Good to go; this is resolved in f9520a5f2d492a71d32882d2d294446d4d285e66.  Enjoy!
